name: flutter_notifications
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  meta: ^1.16.0
  flutter_bloc: ^9.1.1

  #olmasa da olur
  go_router: ^16.2.4
  logger: ^2.6.1
  get_it: ^8.2.0

  #Gerekli paketler
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0


flutter:
  
  uses-material-design: true

